/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configurazione centralizzata del progetto. Letto direttamente da scripts/deploy.sh (bash), dal backend ASP.NET Core (AddJsonFile) e dal frontend Node SSR (readFileSync). Modificare questo file e rieseguire il deploy è sufficiente per applicare la configurazione a tutti i livelli.
 */
export interface GlobalSettings {
  $schema?: string;
  /**
   * Nota descrittiva libera (ignorata dal runtime). Usata in testa ai file per ricordare a cosa serve ciascuno.
   */
  _nota?: string;
  /**
   * Identità dell'app — fonte unica. Nome e versione vivono SOLO qui: scripts/deploy.sh li slugifica per il nome progetto Docker e li passa come build ARG; il frontend li riceve iniettati in environment.ts (navbar, titolo, manifest PWA, meta app-version, rilevamento aggiornamenti).
   */
  project?: {
    /**
     * Nome visualizzato dell'app. Mostrato in navbar/titolo/manifest e slugificato per COMPOSE_PROJECT_NAME (es. 'Mercatino App' → 'mercatino-app').
     */
    name?: string;
    /**
     * Versione dell'app (es. '1.2.0'). Propagata nel meta app-version e nel manifest; usata da VersionCheckService per rilevare gli aggiornamenti.
     */
    version?: string;
    /**
     * Data di ultima modifica dei contenuti, formato italiano GG/MM/AAAA. Alimenta il <lastmod> della sitemap e og:updated_time. Bumpala a mano quando i contenuti cambiano davvero. Se assente/non valida, il build usa la data odierna.
     */
    lastModified?: string;
  };
  /**
   * Configurazione del container frontend (Angular SSR + Node). Letta da scripts/deploy.sh per le variabili docker-compose.
   */
  frontend?: {
    /**
     * Dominio pubblico del sito senza schema (es. 'miodominio.it'). Usato per FRONTEND_BASE_URL, NG_ALLOWED_HOSTS e per derivare Security.CorsOrigins. Se vuoto, il frontend Node SSR accetta solo gli host locali (localhost, 127.0.0.1, [::1]): fail-closed, così in produzione senza hostname il traffico reale viene rifiutato (421) invece di accettare qualsiasi Host. Valorizzarlo (o impostare NG_ALLOWED_HOSTS) per servire il dominio reale.
     */
    hostname?: string;
    /**
     * Porta esposta dal container frontend sull'host Docker. La porta interna del container Node SSR è sempre 3000; questa è la porta del mapping host:container.
     */
    port?: number;
  };
  /**
   * Configurazione dell'esposizione del container backend. Il backend è normalmente interno alla rete Docker; abilitare 'public' solo per API pubbliche o deploy separato.
   */
  backend?: {
    /**
     * Se true, il backend viene esposto su una porta dell'host (richiede docker-compose.backend-exposed.yml). Default: false.
     */
    public?: boolean;
    /**
     * Porta host su cui esporre il backend (usata solo se 'public: true').
     */
    publicPort?: number | null;
  };
  /**
   * Lingue del sito come codici a due lettere: SORGENTE UNICA, consumata in modo indipendente da entrambe le parti — il backend le arricchisce nelle culture .NET tipizzate (RequestLocalization, messaggi d'errore localizzati), il frontend deriva cultura e formattazione (BCP-47, nomi nativi, giorni) via Intl. Lette anche a build/module-load (routing per-lingua, fallback di pickLocaleText).
   */
  Localization?: {
    /**
     * Lingua di default (codice ISO 639-1, es. 'it'). Deve essere inclusa in SupportedLanguages.
     */
    DefaultLanguage?: string;
    /**
     * Lingue supportate come codici a due lettere. Deve includere DefaultLanguage. Per ognuna serve il catalogo i18n (basic/addon) e i file legali.
     *
     * @minItems 1
     */
    SupportedLanguages?: [string, ...string[]];
  };
  /**
   * Sicurezza specifica del progetto: chiavi API, origini CORS, reverse proxy e token JWT. Gli header di sicurezza fissi (uguali per ogni progetto) vivono in security-headers.json, file del template che il progetto figlio non gestisce.
   */
  Security?: {
    /**
     * Configurazione delle API: chiavi accettate e rate limiting.
     */
    ApiConfig?: {
      /**
       * Chiavi API accettate dal backend per le chiamate interne (header X-Api-Key). Il frontend Node SSR usa Security.ApiConfig.Keys[0] per autenticarsi al backend. In produzione usare una stringa casuale di almeno 32 caratteri.
       *
       * @minItems 1
       */
      Keys?: [string, ...string[]];
      /**
       * Rate limiting delle API: soglia globale (per IP) e soglia dedicata al login (POST /auth/login).
       */
      RateLimiting?: {
        /**
         * Attiva/disattiva l'enforcement. Se false, le policy restano registrate ma non contano nulla — utile dietro un WAF/reverse proxy che applica già le proprie soglie.
         */
        Enabled?: boolean;
        /**
         * Limite globale, partizionato per IP client.
         */
        Global?: {
          /**
           * Richieste ammesse per finestra.
           */
          PermitLimit?: number;
          /**
           * Durata della finestra, in secondi.
           */
          WindowSeconds?: number;
        };
        /**
         * Limite su POST /auth/login, partizionato per IP client — pensato per rendere impraticabile il brute force sulle credenziali.
         */
        Login?: {
          /**
           * Richieste ammesse per finestra.
           */
          PermitLimit?: number;
          /**
           * Durata della finestra, in secondi.
           */
          WindowSeconds?: number;
        };
      };
    };
    /**
     * Origini CORS ammesse per il backend. In produzione impostare l'URL completo con schema (es. 'https://miodominio.it'). Lasciare vuoto in sviluppo locale (il backend è interno alla rete Docker).
     */
    CorsOrigins?: string[];
    /**
     * Indica se il backend è dietro un reverse proxy (es. nginx, Cloudflare). Se true, il backend legge l'IP reale da X-Forwarded-For. Impostare a true quando si usa frontend.hostname.
     */
    BehindProxy?: boolean;
    /**
     * Configurazione JWT per il sistema di login. Il login si attiva automaticamente quando SecretKey è valorizzata (>=32 caratteri); lasciare SecretKey vuota per disabilitarlo.
     */
    Token?: {
      /**
       * Chiave segreta per firmare i JWT. Deve essere lunga almeno 32 caratteri in produzione. Lasciare vuota per disabilitare il login.
       */
      SecretKey?: string;
      /**
       * Durata in secondi dei token JWT emessi. Default: 3000 (50 minuti).
       */
      ExpirationSeconds?: number;
    };
    /**
     * Chiave segreta per il servizio di cifratura generico dell'engine (EngineCrypto, AES-256-GCM) — usata ad es. dall'export dati personali (GET /me/data). Volutamente separata da Token.SecretKey: non va derivata da essa né riusata altrove. setup.mjs la genera già alla nascita del progetto, indipendentemente dal login. Rigenerarla con: openssl rand -base64 32.
     */
    CryptoSecret?: string;
  };
  /**
   * Configurazione SMTP del mailer dell'engine (EngineMailer). Contiene SEGRETI (password) → vive in global-settings.local.json. Si attiva come il login: senza Host e FromAddress il mailer resta spento e ogni invio risponde 503. Volutamente generica (SMTP standard): lo stesso codice spedisce con OVH, Brevo, Mailgun, Amazon SES, Gmail o un relay locale cambiando solo questi valori. Per non finire in spam, FromAddress deve stare sul tuo dominio e vanno configurati i record DNS SPF/DKIM/DMARC.
   */
  Mail?: {
    /**
     * Host del server SMTP. Es. OVH: 'ssl0.ovh.net'.
     */
    Host?: string;
    /**
     * Porta SMTP. 587 (STARTTLS) o 465 (SSL/TLS) nella maggior parte dei casi.
     */
    Port?: number;
    /**
     * Modalità di cifratura del canale (TLS sempre obbligatorio). 'Auto' sceglie in sicurezza dalla porta: 465 -> SslOnConnect, altre -> StartTls (mai connessione in chiaro). 'StartTls' tipico su 587; 'SslOnConnect' tipico su 465; 'None' SOLO per relay locali fidati.
     */
    Security?: "Auto" | "None" | "StartTls" | "SslOnConnect";
    /**
     * Utente SMTP (di solito l'indirizzo completo della casella). Vuoto = invio senza autenticazione (relay aperti/locali).
     */
    Username?: string;
    /**
     * Password SMTP della casella. SEGRETO: tienila solo in global-settings.local.json.
     */
    Password?: string;
    /**
     * Mittente di default (usato quando il chiamante non passa un 'from'). DEVE stare sul tuo dominio: è ciò che fa quadrare SPF/DKIM. Mai l'indirizzo di un visitatore.
     */
    FromAddress?: string;
    /**
     * Nome visualizzato di default del mittente (opzionale).
     */
    FromName?: string;
    /**
     * Timeout di connessione/invio in secondi.
     */
    TimeoutSeconds?: number;
    /**
     * Dimensione massima totale degli allegati per messaggio, in byte. Superata -> errore 413. Default 10485760 (10 MB). 0 = nessun limite (sconsigliato su endpoint pubblici).
     */
    MaxAttachmentBytes?: number;
    /**
     * Se true, prima di inviare verifica via DNS che il dominio dei destinatari possa ricevere posta (record MX, fallback A/AAAA): typo di dominio (gmail.con) e domini inesistenti vengono scartati con 400 senza aprire l'SMTP. NON verifica l'esistenza della casella. Default false: nessuna query DNS se non lo accendi.
     */
    VerifyRecipientDomain?: boolean;
  };
  /**
   * Segnalazione errori dell'engine (IErrorReportingService): un POST JSON verso un webhook esterno per ogni eccezione non applicativa o applicativa con status >=500. Non contiene segreti in senso stretto ma vive comunque in global-settings.local.json perché è pubblicazione/ambiente, non identità del progetto. Volutamente senza SDK di terze parti: un webhook HTTP generico, non l'endpoint proprietario di un vendor. Spento di default (WebhookUrl vuoto).
   */
  ErrorReporting?: {
    /**
     * URL del webhook a cui inviare la segnalazione (POST JSON: message, exceptionType, statusCode, path, method, stackTrace troncato, timestamp). Vuoto = spento, nessuna chiamata uscente.
     */
    WebhookUrl?: string;
  };
  /**
   * Identità ed estetica del sito (committabile, del progetto). Iniettata nel frontend al build via environment.ts. I flag di comportamento (showNav, showFooter, showPanel, fixedTopHeader, showLoginInHeader, showNotifications, panelSurface, forceThemeTone, designSystem, isWebApp, onlyPlainImage) sono struttura e vivono in site.ts (`shell` / `isWebApp` / `onlyPlainImage`), insieme a pagine e loginPage; il menu di header/footer e l'icona di brand sono dato risolto a runtime in nav.ts.
   */
  site?: {
    /**
     * Descrizione generale del sito, per-lingua: chiavi = tag lingua (come Localization.SupportedLanguages), valori = testo. Usata in meta description SEO, footer e JSON-LD; il build usa la lingua default per i file statici, l'SSR localizza per richiesta. Accettata anche come singola stringa (legacy), normalizzata sulla lingua default.
     */
    description?: {
      [k: string]: string;
    };
    /**
     * Colore tema principale (hex #RGB o #RRGGBB). Genera la palette OKLCH e il tono testo chiaro/scuro.
     */
    colorTema?: string;
    /**
     * Override opzionale del colore secondario (badge, `.btn-secondary`). Se assente resta la variante muted di `colorTema`. Se presente sostituisce hue e chroma della catena di derivazione: le varianti light/dark/subtle/emphasis restano comunque calcolate e garantite WCAG.
     */
    colorSecondary?: string;
    /**
     * Override opzionale del colore di sfondo (pagina, card, hover, superfici). Se assente resta derivato da `colorTema`. Un solo valore genera automaticamente sia la variante light sia quella dark, come per `colorTema`. Resta comunque una superficie chiara/scura tinta, non un blocco di colore pieno.
     */
    colorBackground?: string;
    /**
     * Override opzionale del colore del testo (corpo e headings). Se assente NON ricade su colorTema ma su colorBackground (che a sua volta è colorTema se nemmeno quello è impostato): testo e sfondo restano sempre intonati tra loro senza sceglierlo esplicitamente. Impostato: override pieno e indipendente. Un solo valore genera automaticamente sia la variante per sfondo chiaro sia quella per sfondo scuro.
     */
    colorText?: string;
    /**
     * Override opzionale del colore informativo (badge/alert '.text-bg-info', '.alert-info', '.btn-outline-info'). A differenza di colorSecondary/colorBackground/colorText NON ha un fallback derivato dal brand: se assente, Bootstrap 5.3 gestisce '--bs-info*' per intero coi suoi blocchi tono-adattivi nativi. warning/success/danger restano sempre fissi (significato universale, non personalizzabile).
     */
    colorInfo?: string;
    /**
     * Effetto particellare di sfondo. Ometti o enable:false per disattivarlo.
     */
    smoke?: {
      enable?: boolean;
      color?: string;
      opacity?: number;
      maximumVelocity?: number;
      particleRadius?: number;
      density?: number;
    };
  };
  /**
   * Valori aggiuntivi liberi, leggibili da entrambi i progetti senza modificare script o codice infrastrutturale.
   *
   * - Backend (ASP.NET Core): ogni chiave è disponibile tramite IConfiguration["Custom:TuaChiave"] o IConfiguration["Custom:Sezione:SottoChiave"]. Supporta oggetti annidati arbitrari.
   * - Frontend Node SSR: disponibile tramite getBr1Settings().Custom in server-env.ts.
   * - Browser Angular: disponibile tramite inject(APP_CUSTOM) (l'SSR la serializza in TransferState e il browser la rilegge in idratazione). NON metterci segreti: è committabile e ora visibile al client.
   *
   * Esempio:
   *   "Custom": {
   *     "FeatureFlags": { "NuovaFunzione": true },
   *     "Analytics": { "TrackingId": "UA-XXXXX" },
   *     "MaxUploadMb": 10
   *   }
   */
  Custom?: {
    [k: string]: unknown;
  };
}
